--
-- PostgreSQL database dump
--

\restrict 3pkEbbh1cX3bBg7cXCDPDmCCruZfehUfBLatHFEDODvcky1l7kckgE3BFhLYyYw

-- Dumped from database version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: employees; Type: TABLE; Schema: public; Owner: django_user
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    department character varying(20) NOT NULL,
    primary_office character varying(10) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    manager_id bigint
);


ALTER TABLE public.employees OWNER TO django_user;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: django_user
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: django_user
--

COPY public.employees (id, username, password, name, email, phone, department, primary_office, role, is_active, created_at, updated_at, manager_id) FROM stdin;
\.


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: django_user
--

SELECT pg_catalog.setval('public.employees_id_seq', 1, false);


--
-- Name: employees employees_email_key; Type: CONSTRAINT; Schema: public; Owner: django_user
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_email_key UNIQUE (email);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: django_user
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: employees employees_username_key; Type: CONSTRAINT; Schema: public; Owner: django_user
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_username_key UNIQUE (username);


--
-- Name: employees_departm_ef7a1f_idx; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_departm_ef7a1f_idx ON public.employees USING btree (department);


--
-- Name: employees_email_c3f945b9_like; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_email_c3f945b9_like ON public.employees USING btree (email varchar_pattern_ops);


--
-- Name: employees_email_f66e96_idx; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_email_f66e96_idx ON public.employees USING btree (email);


--
-- Name: employees_is_acti_e91717_idx; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_is_acti_e91717_idx ON public.employees USING btree (is_active);


--
-- Name: employees_manager_id_0674f795; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_manager_id_0674f795 ON public.employees USING btree (manager_id);


--
-- Name: employees_usernam_b4c359_idx; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_usernam_b4c359_idx ON public.employees USING btree (username);


--
-- Name: employees_username_3c33a186_like; Type: INDEX; Schema: public; Owner: django_user
--

CREATE INDEX employees_username_3c33a186_like ON public.employees USING btree (username varchar_pattern_ops);


--
-- Name: employees employees_manager_id_0674f795_fk_employees_id; Type: FK CONSTRAINT; Schema: public; Owner: django_user
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_manager_id_0674f795_fk_employees_id FOREIGN KEY (manager_id) REFERENCES public.employees(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 3pkEbbh1cX3bBg7cXCDPDmCCruZfehUfBLatHFEDODvcky1l7kckgE3BFhLYyYw

