# Generated by Django 6.0.2 on 2026-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_task_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('wfh', 'Work From Home'), ('client', 'Client'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=20),
        ),
    ]
