# Generated by Django 6.0.2 on 2026-02-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_task_accuracy_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to='attendance.employee')),
                ('members', models.ManyToManyField(related_name='teams', to='attendance.employee')),
            ],
            options={
                'db_table': 'teams',
                'unique_together': {('name', 'manager')},
            },
        ),
    ]
