# Generated by Django 6.0.2 on 2026-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
