# Generated by Django 6.0.2 on 2026-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_task_group_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_assigne_00feb5_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tasks', to='attendance.employee'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='group_id',
        ),
    ]
