# Generated by Django 6.0.2 on 2026-02-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
