# Generated by Django 6.0.2 on 2026-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
