# Generated by Django 6.0.2 on 2026-02-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_attendancerecord_lunch_end_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Surveyors', 'Surveyors'), ('Accounts', 'Accounts'), ('Growth', 'Growth'), ('Others', 'Others')], max_length=20)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_tags', to='attendance.employee')),
            ],
            options={
                'db_table': 'temporary_tags',
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='temporary_t_employe_bc6039_idx')],
            },
        ),
    ]
