# Generated by Django 5.2.5 on 2026-02-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_temporarytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_points', models.IntegerField()),
                ('average_rate', models.FloatField()),
                ('stability_factor', models.FloatField()),
                ('logs', models.JSONField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='attendance.employee')),
            ],
            options={
                'db_table': 'training_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
