# Generated by Django 5.2.11 on 2026-03-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_task_completed_at_task_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_end_lat',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_end_lon',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_end_time',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_start_lat',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_start_lon',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_start_time',
        ),
    ]
