# Generated by Django 4.2.29 on 2026-03-05 09:29

from django.db import migrations, models


def migrate_managers(apps, schema_editor):
    Employee = apps.get_model('attendance', 'Employee')
    for employee in Employee.objects.all():
        if employee.old_manager:
            employee.managers.add(employee.old_manager)

def reverse_migrate_managers(apps, schema_editor):
    Employee = apps.get_model('attendance', 'Employee')
    for employee in Employee.objects.all():
        first_manager = employee.managers.first()
        if first_manager:
            employee.old_manager = first_manager
            employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_remove_attendancerecord_lunch_end_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='old_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='subordinates', to='attendance.employee'),
        ),
        migrations.RunPython(
            code=migrate_managers,
            reverse_code=reverse_migrate_managers,
        ),
        migrations.RemoveField(
            model_name='employee',
            name='old_manager',
        ),
    ]
