# Generated by Django 4.2.29 on 2026-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_multiple_managers_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='request_type',
            field=models.CharField(choices=[('wfh', 'Work From Home'), ('full_day', 'Full Day Leave'), ('half_day', 'Half Day Leave'), ('unblock_attendance', 'Unblock Attendance')], max_length=20),
        ),
    ]
