# Generated by Django 4.2.29 on 2026-03-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_employeerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overseers',
            field=models.ManyToManyField(blank=True, related_name='overseeing_tasks', to='attendance.employee'),
        ),
    ]
