# Generated by Django 4.2.29 on 2026-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_task_overseers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar_emoji',
            field=models.CharField(default='👤', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='theme_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
