# Generated by Django 4.2.29 on 2026-03-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_alter_taskcomment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('skin', 'Skin'), ('hair', 'Hairstyle'), ('brows', 'Brows'), ('eyes', 'Eyes'), ('head', 'Head'), ('nose', 'Nose'), ('mouth', 'Mouth'), ('ears', 'Ears'), ('facial_hair', 'Facial Hair'), ('eyewear', 'Eyewear'), ('headwear', 'Headwear'), ('clothing', 'Clothing'), ('body', 'Body')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'avatar_assets',
            },
        ),
        migrations.CreateModel(
            name='Memoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memoji', to='attendance.employee')),
            ],
            options={
                'db_table': 'memojis',
            },
        ),
    ]
