# Generated by Django 5.2.12 on 2026-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_employeeprofile_avatar_url_memoji_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='managers',
            new_name='mentors',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='reporting_manager',
            new_name='reporting_mentor',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='manager',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='manager',
            new_name='mentor',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='temporarytag',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('mentor', 'Mentor'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'mentor')},
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['end_date'], name='employee_re_end_dat_d9e10a_idx'),
        ),
    ]
