# Generated by Django 6.0.3 on 2026-04-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='request_type',
            field=models.CharField(choices=[('wfh', 'Work From Home'), ('full_day', 'Full Day Leave'), ('half_day', 'Half Day Leave'), ('unblock_attendance', 'Unblock Attendance'), ('task_request', 'Task Request')], max_length=20),
        ),
    ]
