# Generated by Django 6.0.3 on 2026-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
