# Generated by Django 6.0.3 on 2026-04-15 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_alter_attendancerecord_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('day', models.CharField(blank=True, max_length=20)),
                ('is_optional', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='holidays_date_c1d23c_idx'), models.Index(fields=['year'], name='holidays_year_7dff31_idx'), models.Index(fields=['is_optional'], name='holidays_is_opti_e2cee4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HolidayUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='holiday_uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='parsed', max_length=20)),
                ('parsed_count', models.IntegerField(default=0)),
                ('saved_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_uploads', to='attendance.employee')),
            ],
            options={
                'db_table': 'holiday_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='attendance.holiday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_holidays', to='attendance.employee')),
            ],
            options={
                'db_table': 'user_holidays',
                'indexes': [models.Index(fields=['user'], name='user_holida_user_id_501250_idx'), models.Index(fields=['holiday'], name='user_holida_holiday_5e3867_idx')],
                'unique_together': {('user', 'holiday')},
            },
        ),
    ]
