# Generated by Django 6.0.3 on 2026-04-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_holiday_holidayupload_userholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='taken_cl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='total_cl',
            field=models.IntegerField(default=12),
        ),
    ]
