# Generated by Django 6.0.3 on 2026-04-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_employeeprofile_taken_cl_employeeprofile_total_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_working_day',
            field=models.BooleanField(default=False),
        ),
    ]
