# Generated by Django 6.0.4 on 2026-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_taskattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='mentor',
        ),
        migrations.AddField(
            model_name='task',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='supervised_tasks', to='attendance.employee'),
        ),
    ]
