# Generated by Django 5.2.12 on 2026-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
