# Generated by Django 6.0.4 on 2026-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_taskstep_actual_hours_taskstep_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
