# Generated by Django 6.0.4 on 2026-05-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0047_taskstep_actual_hours_taskstep_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='escalation_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_projects', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='escalation_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='sla_response_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
