# Generated by Django 6.0.4 on 2026-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_project_assignees_project_client_facing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='escalation_contact',
        ),
        migrations.AddField(
            model_name='project',
            name='escalation_contacts',
            field=models.ManyToManyField(blank=True, related_name='escalation_projects', to='attendance.employee'),
        ),
    ]
