# Generated by Django 6.0.4 on 2026-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_remove_project_escalation_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='escalation_matrix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
